let sublocations = {
    "RootCultist": "MarrowPass",
    "RootWraith": "TheHiddenSanctum",
    "RootBrute": "SunkenPassage",
    "Brabus": "CutthroatChannel",
    "RootTumbleweed": "TheTangledPass",
    "RootEnt": "TheChokingHollow",
    "RootDragon": "TheAshYard",
    "HuntersHideout": "HiddenGrotto",
    "MadMerchant": "Junktown",
    "LizAndLiz": "TheWarren",
    "LastWill": "FindMonkeyKey",
    "RootShrine": "TheGallows",
    "SwarmMaster": "TheIronRift",
    "HoundMaster": "TheBurrows",
    "Sentinel": "ShackledCanyon",
    "Vyr": "TheArdentTemple",
    "WastelandGuardian": "LoomOfTheBlackSun",
    "TheHarrow": "TheBunker",
    "TheLostGantry": "ConcourseOfTheSun",
    "ArmorVault": "VaultOfTheHeralds",
    "TheCleanRoom": "ThePurgeHall",
    "SlimeHulk": "TheDrownedTrench",
    "Fatty": "TheFetidGlade",
    "Tyrant": "TheCapillary",
    "SwampGuardian": 'The Grotto',
    'KinCaller': "TheHallOfJudgement",
    "BlinkFiend": "Widow'sPass",
    'StuckMerchant': "MerchantDungeon",
    'BlinkThief': 'ForgottenUndercroft',
    "StormCaller": "Heretic'sNest",
    "ImmolatorAndZephyr": "WitheringVillage",
    'Wolf': "TheScaldingGlade",
    'TotemFather': "TheScaldingGlade",
    'TheRisen': "Ahanae'sLament",
    'DoeShrine': "Widow'sVestry",
    'WolfShrine': "Martyr'sSanctuary",
    "Splitter": "ResearchStationAlpha",
    "BarbTerror": "NeedleLair",
    "QueensTemple": "IskalTemple",
    "BrainBug": "StrangePass",
    "Wisp": "CircletHatchery",
    "FetidPool": "FetidPools",
    "FlickeringHorror": "HallOfWhispers",
    "RatRider": "TheCrimsonHold",
    "IceSkimmer": "TheFrieranSea",
    "UrikkiBlademasters": "ChasmicVent",
    "ShamanFlames": "Grave of theElders",
    "BlizzardMage": "Wuthering Keep",
    "WarningTotems": "Magir'sDirge"
}

let mainLocations = {
    "City Overworld Zone1": "Fairview",
    "City Overworld Zone2": "Westcourt",
    "Wasteland Overworld Zone1": "TheEasternWind",
    "Wasteland Overworld Zone2": "TheScouringWaste",
    "Jungle Overworld Zone1": "TheVerdantStrand",
    "Jungle Overworld Zone2": "TheScaldingGlade",
    "Swamp Overworld Zone1": "TheFetidGlade",
    "Swamp Overworld Zone2": "TheMistFen"
}

let eventNames = {
    'FlickeringHorror': 'DreamEater',
    'Wisp': 'HiveWisps',
    'LizAndLiz': 'LizChicagoTypewriter',
    'Fatty': 'TheUncleanOne',
    'WastelandGuardian': 'Claviger',
    'RootEnt': 'EntBoss',
    'Wolf': 'TheRavager',
    'RootDragon': 'Singe',
    'SwarmMaster': 'Scourge',
    'RootWraith': 'Shroud',
    'RootTumbleweed': 'TheMangler',
    'Kincaller': 'Warden',
    'Tyrant': 'Thrall',
    'Vyr': 'ShadeAndShatter',
    'ImmolatorAndZephyr': 'ScaldAndSear',
    'RootBrute': 'Gorefist',
    'SlimeHulk': 'Canker',
    'BlinkFiend': 'Onslaught',
    'Sentinel': 'Raze',
    'Penitent': 'Letos Amulet',
    'LastWill': 'SupplyRunAssaultRifle',
    'SwampGuardian': 'Ixillis',
    'Splitter': 'RiphideLetosArmor',
    "UrikkiBlademasters": "Tian, theAssassin",
    "RatRider": "Brudvaak, theRider andVargr, theWarg",
    "Afterbirth": "KrallMother",
    "IceSkimmer": "Sebum",
    "SerpentsFang": "Serpent'sFang",
    "ShamanFlames": "GraveSiege",
    "BlizzardMage": "Ikro, theIceConjurer",
    "StormCaller": "Stormcaller",
    "OldManAndConstruct": "Wud"
}

module.exports = {
    sublocations,
    mainLocations,
    eventNames
}